# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
use_frameworks!


target 'firebase-auth-ios' do

  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'firebase-auth-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'firebase-auth-iosUITests' do
    # Pods for testing
  end

end
